# Generated by Django 2.0.10 on 2019-02-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dioBase',
            new_name='obatBase',
        ),
    ]
