# Generated by Django 2.0.10 on 2019-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190211_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='obatbase',
            name='categoryObat2',
            field=models.CharField(choices=[('Pilih', 'Pilih Salah Satu'), ('Batuk', 'Obat Batuk'), ('Asma', 'Obat Asma')], default='Pilih', max_length=10),
        ),
    ]
