# Generated by Django 2.0.10 on 2019-02-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190224_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obatbase',
            name='PIC',
        ),
    ]
