# Generated by Django 2.0.10 on 2019-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_obatbase_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='obatbase',
            name='pic',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
